apiVersion: v1
kind: Service
metadata:
  labels:
    app: theater
  name: theater-outbound-service
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: theater-outbound
  type: LoadBalancer
