apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer
  name: customer-outbound-service
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: customer-outbound
  type: LoadBalancer
